- type: job
  parent: AU14Jobk9handlerBase
  id: AU14JobThirdPartyK9Handler
  name: K9 Handler
  description: K9 Handler
  setPreference: false
  ranks:
    RMCRankStaffSergeant: []
  startingGear: AU14GearThirdPartyK9Handler
  icon: "AU14JobIconGovK9Handler"
  requireAdminNotify: false
  spawnMenuRoleName: K9 Handler
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
    - Colonist
    - aumed
  # - AU14GovforCorpsman
  # - AU14GovforSquad
  overwatchSortPriority: -2
  overwatchRoleName: K9 Handler#
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: AU14SkillPresetPlatoonHospitalCorpsman
    - type: JobPrefix
      prefix: au14-job-prefix-govfork9handler
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true

- type: startingGear
  id: AU14GearThirdPartyK9Handler
  equipment:
    jumpsuit: AU14UniversalBlackFatigues
    id: AU14IDCardSquadK9Handler
    ears: AU14HeadsetGovforCommand
    eyes: RMCGlassesMedicalHUDGlasses
    outerClothing: AU14WYPPOArmor
    shoes: CMBootsBlack
    ears2: RMCM5CameraGear
    head: ArmorHelmetPMCFieldOfficer
    neck: RMCWhistle
    gloves: AU14PVEHandsInsulatedBlackMarine
    belt: RMCM1984BeltFilled
    pocket1: RMCPouchMedkitPMCFilled
    pocket2: AU14PouchAutoinjectorFilledMilitaryDoctor
    back: CMBackpackMedical
    mask: CMTarbackCigar
  storage:
    back:
    - CMBurnKit10
    - CMBurnKit10
    - CMTraumaKit10
    - CMTraumaKit10
    - CMPillCanisterBicaridine
    - CMPillCanisterKelotane
    - CMPillCanisterDexalin
    - CMPillCanisterDylovene
    - CMPillCanisterInaprovaline
    - CMPillCanisterTricordrazine
    - RMCPillCanisterIron
    - AU14IVFoldableFolded
    - CMDefibrillator
    - RMCRadioHandheldColonyOff
  inhand:
  - RMCZippo

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORK9Handler
  name: (DO NOT MAP) Spawn Point GOVFOR K9 Handler
  components:
  - type: SpawnPoint
    job_id: AU14JobThirdPartyK9Handler
  - type: Sprite
    state: syn_spawn

- type: jobIcon
  parent: CMJobIconBase
  id: AU14JobIconGovK9Handler
  icon:
    sprite: _AU14/Interface/au14govforjobicons.rsi
    state: govfor_k9handler
