- type: job
  parent: AU14JobRadioTelephoneOperatorBase
  id: AU14JobGOVFORRadioTelephoneOperator
  name: au14-job-name-radiotelephoneoperator
  description: au14-job-description-radiotelephoneoperator
  setPreference: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
  ranks:
    #RMCRankStaffSergeant:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORRadioTelephoneOperator
    #  time: 360000 # 100 hours
    #RMCRankSergeant:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORRadioTelephoneOperator
    #  time: 180000 # 50 hours
    #RMCRankCorporal:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORRadioTelephoneOperator
    #  time: 86400 # 24 hours
    #RMCRankLanceCorporal:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORRadioTelephoneOperator
    #  time: 36000 # 10 hours
    RMCRankCorporal: []
  startingGear: AU14GearGOVFORRadioTelephoneOperator
  dummyStartingGear: AU14GearGOVFORRadioTelephoneOperatorDummy
  icon: "AU14JobIconSarge"
  requireAdminNotify: false
  spawnMenuRoleName: Fireteam Leader (GOVFOR)
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforFTL
  overwatchSortPriority: -3
  overwatchRoleName: Fire Team Leaders
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonRTO
    - type: JobPrefix
      prefix: au14-job-prefix-radiotelephoneoperator
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: tl
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
    - type: UserIFF
      factions:
      - GOVFOR
  hidden: false

- type: startingGear
  id: AU14GearGOVFORRadioTelephoneOperator
  equipment:
    id: AU14JobIDCardGOVFORRadioTelephoneOperator
    ears: AU14HeadsetGovforMarineFTL
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORRadioTelephoneOperator
  name: Spawn Point GOVFOR Radio Telephone Operator
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORRadioTelephoneOperator
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORRadioTelephoneOperatorDummy
  equipment:
    outerClothing: AU14ArmorM3JungleOne
    shoes: CMBootsBrown
    head: AU14JungleBoonieHat
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetGovforMarineFTL
