- type: job
  parent: AU14JobPlatOpBase
  id: AU14JobGOVFORPlatOp
  name: au14-job-name-govforplatop
  description: au14-job-description-govforplatop
  setPreference: true
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 25
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    #RMCRankCaptain:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORPlatOp
    #  time: 360000 # 100 hours
    RMCRankFirstLT:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatOp
      time: 86400 # 24 hours
    RMCRankSecondLT: []
  startingGear: AU14GearGOVFORPlatOp
  dummyStartingGear: AU14GearGOVFORPlatOpDummy
  icon: "AU14JobIconOpsOfc"
  requireAdminNotify: true
  spawnMenuRoleName: Junior Officer (GOVFOR)
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforCommand
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonJuniorOfficer
    - type: JobPrefix
      prefix: au14-job-prefix-govforplatop
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: so
    - type: UserIFF
      factions:
      - GOVFOR
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
  hidden: false

- type: startingGear
  id: AU14GearGOVFORPlatOp
  equipment:
    id: AU14IDCardGOVFORPlatOp
    ears: AU14HeadsetGovforCommand
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORPlatOp
  name: Spawn Point GOVFOR Platoon Operations Officer
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORPlatOp
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORPlatOpDummy
  equipment:
    shoes: CMBootsBlack
    head: AU14JunglePatrolCap
    jumpsuit: CMJumpsuitXOFormal
    ears: AU14HeadsetGovforCommand
