- type: job
  parent: AU14JobPlatoonCorpsmanBase
  id: AU14JobGOVFORPlatoonCorpsman
  name: au14-job-name-govforplatooncorpsman
  description: au14-job-description-govforplatooncorpsman
  setPreference: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
  ranks:
    #RMCRankSergeant:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORPlatoonCorpsman
    #  time: 180000 # 50 hours
    #RMCRankCorporal:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORPlatoonCorpsman
    #  time: 86400 # 24 hours
    RMCRankLanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatoonCorpsman
      time: 36000 # 10 hours
    RMCRankPrivateFirstClass: []
  startingGear: AU14GearGOVFORPlatoonCorpsman
  dummyStartingGear: AU14GearGOVFORCorpsmanDummy
  icon: "AU14JobIconCorpsman"
  requireAdminNotify: false
  spawnMenuRoleName: Hospital Corpsman (GOVFOR)
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforCorpsman
  - AU14GovforSquad
  overwatchSortPriority: -2
  overwatchRoleName: Hospital Corpsmen
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonHospitalCorpsman
    - type: JobPrefix
      prefix: au14-job-prefix-govforplatooncorpsman
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: medic
    - type: UserIFF
      factions:
      - GOVFOR
  hidden: false

- type: startingGear
  id: AU14GearGOVFORPlatoonCorpsman
  equipment:
    id: AU14JobIDCardGOVFORPlatoonCorpsman
    ears: AU14HeadsetGovforMarine
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORPlatoonCorpsman
  name: Spawn Point GOVFOR Squad Sergeant
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORPlatoonCorpsman
  - type: Sprite
    state: syn_spawn



- type: startingGear
  id: AU14GearGOVFORCorpsmanDummy
  equipment:
    outerClothing: AU14ArmorM3JungleOne
    gloves: CMHandsLatex
    shoes: CMBootsBlack
    head: AU14JungleM10CorpsmanHelmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetGovforMarine
