- type: job
  parent: AU14JobPlatCoBase
  id: AU14JobGOVFORPlatCo
  name: au14-job-name-govforplatco
  description: au14-job-description-govforplatco
  setPreference: true
  canBeAntag: false
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 # 10 hours
  - !type:AgeRequirement
    requiredAge: 30
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxiety
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
   # RMCRankLieutenantColonel:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORPlatCo
    #  time: 360000 # 100 hours
    RMCRankMajor:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatCo
      time: 180000 # 50 hours
    #RMCRankCaptain:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORPlatCo
    #  time: 36000 # 10 hours
    RMCRankCaptain: []
  startingGear: AU14GearGOVFORPlatCo
  dummyStartingGear: AU14GearGOVFORPlatCoDummy
  icon: "AU14JobIconPlatCo"
  requireAdminNotify: true
  spawnMenuRoleName: Platoon Commander (GOVFOR)
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govforplatco
  accessGroups:
  - AU14GovforCommand
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: CommendationGiver
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonCommander
    - type: JobPrefix
      prefix: au14-job-prefix-govforplatco
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: co
    - type: UserIFF
      factions:
      - GOVFOR
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
  hidden: false

- type: startingGear
  id: AU14GearGOVFORPlatCo
  equipment:
    id: AU14IDCardGOVFORPlatCo
    ears: AU14HeadsetGovforCommand
  inhand:
    -  RMCTabletGovfor
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORPlatCo
  name: Spawn Point GOVFOR Platoon Commander
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORPlatCo
  - type: Sprite
    state: syn_spawn


- type: startingGear
  id: AU14GearGOVFORPlatCoDummy
  equipment:
    shoes: CMBootsBlack
    head: CMHeadCapPeakedFormal
    jumpsuit: CMJumpsuitXOFormal
    ears: AU14HeadsetGovforCommand
