- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobGOVFORSquadRifleman
  name: au14-job-name-govforsquadrifleman
  description: au14-job-description-govforsquadrifleman
  setPreference: true
  playTimeTracker: AU14JobGOVFORSquadRifleman
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
  ranks:
    #RMCRankCorporal:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORSquadRifleman
    #  time: 180000 # 50 hours
    #RMCRankLanceCorporal:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORSquadRifleman
    #  time: 86400 # 24 hours
    RMCRankPrivateFirstClass:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 36000 # 10 hours
    RMCRankPrivate: []
  startingGear: AU14GearGOVFORSquadRifleman
  dummyStartingGear: AU14GearGOVFORRiflemanDummy
  icon: "AU14JobIconGovRifleman"
  requireAdminNotify: false
  spawnMenuRoleName: Rifleman (GOVFOR)
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforSquad
  hasIcon: false
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonRifleman
    - type: JobPrefix
      prefix: au14-job-prefix-govforsquadrifleman
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: private
    - type: UserIFF
      factions:
      - GOVFOR
  hidden: false

- type: startingGear
  id: AU14GearGOVFORSquadRifleman
  equipment:
    id: AU14IDCardSquadRifleman
    ears: AU14HeadsetGovforMarine
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORSquadRifleman
  name: Spawn Point GOVFOR Squad Rifleman
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORSquadRifleman
  - type: Sprite
    state: syn_spawn



- type: startingGear
  id: AU14GearGOVFORRiflemanDummy
  equipment:
    outerClothing: AU14ArmorM3JungleThree
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetGovforMarine
