- type: job
  parent: AU14JobSectionSergeantBase
  id: AU14JobGOVFORSectionSergeant
  name: au14-job-name-govforSSG
  description: au14-job-description-govforSSG
  setPreference: false
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5 hours
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    #RMCRankMasterSergeant:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORSectionSergeant
    #  time: 360000 # 100 hours
    #RMCRankGunnerySergeant:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORSectionSergeant
    #  time: 180000 # 50 hours
    RMCRankStaffSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSectionSergeant
      time: 36000 # 10 hours
    RMCRankSergeant: []
  startingGear: AU14GearGOVFORSectionSergeant
  dummyStartingGear: AU14GearGOVFORPlatoonSergantDummy
  icon: "AU14JobIconPlatoonSarge"
  requireAdminNotify: true
  spawnMenuRoleName: Platoon Sergeant (GOVFOR)
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforCommand
  overwatchSortPriority: -6
  overwatchShowName: true
  overwatchRoleName: Platoon Sergeant
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonSeniorSergeant
    - type: JobPrefix
      prefix: au14-job-prefix-govforSSG
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: xo
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
    - type: UserIFF
      factions:
      - GOVFOR
  hidden: false

- type: startingGear
  id: AU14GearGOVFORSectionSergeant
  equipment:
    id: AU14IDCardSecSergeant
    ears: AU14HeadsetGovforMarine
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORSectionSergeant
  name: Spawn Point GOVFOR Section Sergeant
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORSectionSergeant
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORPlatoonSergantDummy
  equipment:
    outerClothing: AU14ArmorM3JungleTwo
    shoes: CMBootsBrown
    head: AU14JunglePatrolCap
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetGovforMarine
