- type: job
  parent: AU14JobRadioTelephoneOperatorBase
  id: AU14JobGOVFORRadioTelephoneOperatorWYPMC
  name: PMC Communications Specialist
  description: au14-job-description-radiotelephoneoperator
  setPreference: false
  ranks:
    AU14RankWeYuSeniorOperator:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORRadioTelephoneOperator
      time: 108000 # 30 hours
    AU14RankWeYuOperator: []
  startingGear: AU14GearGOVFORRadioTelephoneOperator
  dummyStartingGear: AU14GearGOVFORRadioTelephoneOperatorDummy
  icon: "AU14JobIconRTO"
  requireAdminNotify: false
  spawnMenuRoleName: Fireteam Leader (WYPMC)
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforFTL
  overwatchSortPriority: -5
  overwatchRoleName: Radio Telephone Operator
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 3
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORRadioTelephoneOperatorWYPMC
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
  hidden: true
